企业微信 增加 将自建应用获取的corpid转换为第三方应用获取的corpid,将自建应用获取的userid转换为第三方应用获取的userid 接口
w7corp/easywechat pull request #2279
Opened 2021-12-01 08:59 UTC by canren

easywechat版本5.x

新加接口:

* 将自建应用获取的corpid转换为第三方应用获取的corpid
[https://open.work.weixin.qq.com/api/doc/90001/90143/95327#1.4%20corpid%E8%BD%AC%E6%8D%A2](https://open.work.weixin.qq.com/api/doc/90001/90143/95327#1.4%20corpid%E8%BD%AC%E6%8D%A2)
* 将自建应用获取的userid转换为第三方应用获取的userid
[https://open.work.weixin.qq.com/api/doc/90001/90143/95327#2.4%20userid%E7%9A%84%E8%BD%AC%E6%8D%A2](https://open.work.weixin.qq.com/api/doc/90001/90143/95327#2.4%20userid%E7%9A%84%E8%BD%AC%E6%8D%A2)

修复问题:
* phpstan报错修复
* 自动化测试抛出异常修复

有个疑问 该测试文件 `tests/Payment/ApplicationTest.php line:39` 是否有用,这地方一直报错,我就把这几行删除了,如果有用的话,请告知我恢复一下,谢谢
```

        // test calling nonexistent method
        $this->expectErrorMessageMatches('/does not have a method \"noncexistentMethod\"/');
        $app->noncexistentMethod('foo');

```

2021-12-01 10:59 UTC, overtrue requested changes

2021-12-02 02:29 UTC, canren commented on src/Work/CorpGroup/Client.php
> +    public function batchUseridToOpenuserid(array $useridList)
好的,已经修复

2021-12-02 02:39 UTC, canren commented
企业微信帐号ID安全性全面升级,最近注释变动很频繁

2021-12-02 02:39 UTC, canren commented
[https://open.work.weixin.qq.com/api/doc/90001/90143/95327?taskid=4294967538&notreplace=true](https://open.work.weixin.qq.com/api/doc/90001/90143/95327?taskid=4294967538&notreplace=true)

2021-12-02 03:08 UTC, overtrue commented on src/Work/CorpGroup/Client.php
> +    public function corpToOpenCorpid(string $corpId)
getOpenCorpid 吧

2021-12-02 03:23 UTC, merged