3.x 视频号更新组件 添加场景接入申请接口，退款单接口格式调整
w7corp/easywechat pull request #2519
Opened 2022-06-29 03:02 UTC by hpppenely

本次更新两个部分  添加场景接入申请接口，退款单接口格式调整

2022-06-29 13:41 UTC, overtrue commented on src/MiniProgram/Transactions/Transactions.php
> +    protected function uploadMedia($type, $path, $respType, array $form = [])
破坏了原有的 API 哈，这不行的

2022-06-29 14:02 UTC, overtrue commented on src/MiniProgram/Transactions/Transactions.php
> +    protected function uploadMedia($type, $path, $respType, array $form = [])
不能改动原有参数的，否则原来调用的人会出问题，新增参数只能加到后面或者做兼容处理

2022-06-30 03:48 UTC, overtrue commented
冲突了

2022-07-01 03:48 UTC, overtrue requested changes

2022-07-01 03:48 UTC, overtrue commented on src/MiniProgram/Transactions/AfterSale/EcAfterSale.php
> +    public function get(array $params)
这样破坏了兼容性

2022-07-01 03:48 UTC, overtrue commented on src/MiniProgram/Transactions/AfterSale/EcAfterSale.php
> +    public function acceptRefund(array $params)
同理，没法向下兼容

2022-07-01 03:48 UTC, overtrue commented on src/MiniProgram/Transactions/AfterSale/EcAfterSale.php
> +    public function reject(string $outAftersaleId)
这个是接口改动了？

2022-07-04 05:46 UTC, hpppenely commented on src/MiniProgram/Transactions/AfterSale/EcAfterSale.php
> +    public function reject(string $outAftersaleId)
这三个是我改动的，这个接口文件是我上次提交新加的，由于当时对接口不熟悉，考虑的有点少，原有写法有点问题，所以需要更新下

2022-07-04 05:50 UTC, hpppenely commented on src/MiniProgram/Transactions/AfterSale/EcAfterSale.php
> +    public function reject(string $outAftersaleId)
微信官方文档里$outAftersaleId, $aftersaleId 这两个参数是二选一的，我提交第一版时，没注意这里，所以用$params 数组兼容处理下，在自己代码里边去判断，这样比较合理。辛苦帮忙审核下

2022-07-04 06:20 UTC, merged